<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
             ['name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'phone_code' => '93', 'nationality' => 'Afghan'],
            ['name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'phone_code' => '355', 'nationality' => 'Albanian'],
            ['name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'phone_code' => '213', 'nationality' => 'Algerian'],
            ['name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'phone_code' => '376', 'nationality' => 'Andorran'],
            ['name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'phone_code' => '244', 'nationality' => 'Angolan'],
            ['name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'phone_code' => '1', 'nationality' => 'Antiguan or Barbudan'],
            ['name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'phone_code' => '54', 'nationality' => 'Argentine'],
            ['name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'phone_code' => '374', 'nationality' => 'Armenian'],
            ['name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'phone_code' => '61', 'nationality' => 'Australian'],
            ['name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'phone_code' => '43', 'nationality' => 'Austrian'],
            ['name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'phone_code' => '994', 'nationality' => 'Azerbaijani, Azeri'],
            ['name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'phone_code' => '1', 'nationality' => 'Bahamian'],
            ['name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'phone_code' => '973', 'nationality' => 'Bahraini'],
            ['name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'phone_code' => '880', 'nationality' => 'Bangladeshi'],
            ['name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'phone_code' => '1', 'nationality' => 'Barbadian'],
            ['name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'phone_code' => '375', 'nationality' => 'Belarusian'],
            ['name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'phone_code' => '32', 'nationality' => 'Belgian'],
            ['name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'phone_code' => '501', 'nationality' => 'Belizean'],
            ['name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'phone_code' => '229', 'nationality' => 'Beninese, Beninois'],
            ['name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'phone_code' => '975', 'nationality' => 'Bhutanese'],
            ['name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'phone_code' => '591', 'nationality' => 'Bolivian'],
            ['name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'phone_code' => '387', 'nationality' => 'Bosnian or Herzegovinian'],
            ['name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'phone_code' => '267', 'nationality' => 'Motswana, Botswanan'],
            ['name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'phone_code' => '55', 'nationality' => 'Brazilian'],
            ['name' => 'Brunei Darussalam', 'iso2' => 'BN', 'iso3' => 'BRN', 'phone_code' => '673', 'nationality' => 'Bruneian'],
            ['name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'phone_code' => '359', 'nationality' => 'Bulgarian'],
            ['name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'phone_code' => '226', 'nationality' => 'Burkinabé'],
            ['name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'phone_code' => '257', 'nationality' => 'Burundian'],
            ['name' => 'Cabo Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'phone_code' => '238', 'nationality' => 'Cabo Verdean'],
            ['name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'phone_code' => '855', 'nationality' => 'Cambodian'],
            ['name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'phone_code' => '237', 'nationality' => 'Cameroonian'],
            ['name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'phone_code' => '1', 'nationality' => 'Canadian'],
            ['name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'phone_code' => '236', 'nationality' => 'Central African'],
            ['name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'phone_code' => '235', 'nationality' => 'Chadian'],
            ['name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'phone_code' => '56', 'nationality' => 'Chilean'],
            ['name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'phone_code' => '86', 'nationality' => 'Chinese'],
            ['name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'phone_code' => '57', 'nationality' => 'Colombian'],
            ['name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'phone_code' => '269', 'nationality' => 'Comoran, Comorian'],
            ['name' => 'Congo', 'iso2' => 'CG', 'iso3' => 'COG', 'phone_code' => '242', 'nationality' => 'Congolese'],
            ['name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'phone_code' => '506', 'nationality' => 'Costa Rican'],
            ['name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'phone_code' => '385', 'nationality' => 'Croatian'],
            ['name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'phone_code' => '53', 'nationality' => 'Cuban'],
            ['name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'phone_code' => '357', 'nationality' => 'Cypriot'],
            ['name' => 'Czechia', 'iso2' => 'CZ', 'iso3' => 'CZE', 'phone_code' => '420', 'nationality' => 'Czech'],
            ['name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'phone_code' => '45', 'nationality' => 'Danish'],
            ['name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'phone_code' => '253', 'nationality' => 'Djiboutian'],
            ['name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'phone_code' => '1', 'nationality' => 'Dominican'],
            ['name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'phone_code' => '1', 'nationality' => 'Dominican'],
            ['name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'phone_code' => '593', 'nationality' => 'Ecuadorian'],
            ['name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'phone_code' => '20', 'nationality' => 'Egyptian'],
            ['name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'phone_code' => '503', 'nationality' => 'Salvadoran'],
            ['name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'phone_code' => '240', 'nationality' => 'Equatorial Guinean, Equatoguinean'],
            ['name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'phone_code' => '291', 'nationality' => 'Eritrean'],
            ['name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'phone_code' => '372', 'nationality' => 'Estonian'],
            ['name' => 'Eswatini', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'phone_code' => '268', 'nationality' => 'Swazi'],
            ['name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'phone_code' => '251', 'nationality' => 'Ethiopian'],
            ['name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'phone_code' => '679', 'nationality' => 'Fijian'],
            ['name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'phone_code' => '358', 'nationality' => 'Finnish'],
            ['name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'phone_code' => '33', 'nationality' => 'French'],
            ['name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'phone_code' => '241', 'nationality' => 'Gabonese'],
            ['name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'phone_code' => '220', 'nationality' => 'Gambian'],
            ['name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'phone_code' => '995', 'nationality' => 'Georgian'],
            ['name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'phone_code' => '49', 'nationality' => 'German'],
            ['name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'phone_code' => '233', 'nationality' => 'Ghanaian'],
            ['name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'phone_code' => '30', 'nationality' => 'Greek, Hellenic'],
            ['name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'phone_code' => '1', 'nationality' => 'Grenadian'],
            ['name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'phone_code' => '502', 'nationality' => 'Guatemalan'],
            ['name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'phone_code' => '224', 'nationality' => 'Guinean'],
            ['name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'phone_code' => '245', 'nationality' => 'Bissau-Guinean'],
            ['name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'phone_code' => '592', 'nationality' => 'Guyanese'],
            ['name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'phone_code' => '509', 'nationality' => 'Haitian'],
            ['name' => 'Holy See', 'iso2' => 'VA', 'iso3' => 'VAT', 'phone_code' => '379', 'nationality' => 'Vatican'],
            ['name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'phone_code' => '504', 'nationality' => 'Honduran'],
            ['name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'phone_code' => '36', 'nationality' => 'Hungarian, Magyar'],
            ['name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'phone_code' => '354', 'nationality' => 'Icelandic'],
            ['name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'phone_code' => '91', 'nationality' => 'Indian'],
            ['name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'phone_code' => '62', 'nationality' => 'Indonesian'],
            ['name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'phone_code' => '98', 'nationality' => 'Iranian, Persian'],
            ['name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'phone_code' => '964', 'nationality' => 'Iraqi'],
            ['name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'phone_code' => '353', 'nationality' => 'Irish'],
            ['name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'phone_code' => '972', 'nationality' => 'Israeli'],
            ['name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'phone_code' => '39', 'nationality' => 'Italian'],
            ['name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'phone_code' => '1', 'nationality' => 'Jamaican'],
            ['name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'phone_code' => '81', 'nationality' => 'Japanese'],
            ['name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'phone_code' => '962', 'nationality' => 'Jordanian'],
            ['name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'phone_code' => '7', 'nationality' => 'Kazakhstani, Kazakh'],
            ['name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'phone_code' => '254', 'nationality' => 'Kenyan'],
            ['name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'phone_code' => '686', 'nationality' => 'I-Kiribati'],
            ['name' => 'Korea (North)', 'iso2' => 'KP', 'iso3' => 'PRK', 'phone_code' => '850', 'nationality' => 'North Korean'],
            ['name' => 'Korea (South)', 'iso2' => 'KR', 'iso3' => 'KOR', 'phone_code' => '82', 'nationality' => 'South Korean'],
            ['name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'phone_code' => '965', 'nationality' => 'Kuwaiti'],
            ['name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'phone_code' => '996', 'nationality' => 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz'],
            ['name' => 'Lao People\'s Democratic Republic', 'iso2' => 'LA', 'iso3' => 'LAO', 'phone_code' => '856', 'nationality' => 'Lao, Laotian'],
            ['name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'phone_code' => '371', 'nationality' => 'Latvian'],
            ['name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'phone_code' => '961', 'nationality' => 'Lebanese'],
            ['name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'phone_code' => '266', 'nationality' => 'Basotho'],
            ['name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'phone_code' => '231', 'nationality' => 'Liberian'],
            ['name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'phone_code' => '218', 'nationality' => 'Libyan'],
            ['name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'phone_code' => '423', 'nationality' => 'Liechtenstein'],
            ['name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'phone_code' => '370', 'nationality' => 'Lithuanian'],
            ['name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'phone_code' => '352', 'nationality' => 'Luxembourg, Luxembourgish'],
            ['name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'phone_code' => '261', 'nationality' => 'Malagasy'],
            ['name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'phone_code' => '265', 'nationality' => 'Malawian'],
            ['name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'phone_code' => '60', 'nationality' => 'Malaysian'],
            ['name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'phone_code' => '960', 'nationality' => 'Maldivian'],
            ['name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'phone_code' => '223', 'nationality' => 'Malian, Malinese'],
            ['name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'phone_code' => '356', 'nationality' => 'Maltese'],
            ['name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'phone_code' => '692', 'nationality' => 'Marshallese'],
            ['name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'phone_code' => '222', 'nationality' => 'Mauritanian'],
            ['name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'phone_code' => '230', 'nationality' => 'Mauritian'],
            ['name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'phone_code' => '52', 'nationality' => 'Mexican'],
            ['name' => 'Micronesia (Federated States of)', 'iso2' => 'FM', 'iso3' => 'FSM', 'phone_code' => '691', 'nationality' => 'Micronesian'],
            ['name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'phone_code' => '377', 'nationality' => 'Monégasque, Monacan'],
            ['name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'phone_code' => '976', 'nationality' => 'Mongolian'],
            ['name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'phone_code' => '382', 'nationality' => 'Montenegrin'],
            ['name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'phone_code' => '212', 'nationality' => 'Moroccan'],
            ['name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'phone_code' => '258', 'nationality' => 'Mozambican'],
            ['name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'phone_code' => '95', 'nationality' => 'Burmese'],
            ['name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'phone_code' => '264', 'nationality' => 'Namibian'],
            ['name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'phone_code' => '674', 'nationality' => 'Nauruan'],
            ['name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'phone_code' => '977', 'nationality' => 'Nepali, Nepalese'],
            ['name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'phone_code' => '31', 'nationality' => 'Dutch, Netherlandic'],
            ['name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'phone_code' => '64', 'nationality' => 'New Zealand, NZ'],
            ['name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'phone_code' => '505', 'nationality' => 'Nicaraguan'],
            ['name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'phone_code' => '227', 'nationality' => 'Nigerien'],
            ['name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'phone_code' => '234', 'nationality' => 'Nigerian'],
            ['name' => 'North Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'phone_code' => '389', 'nationality' => 'Macedonian'],
            ['name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'phone_code' => '47', 'nationality' => 'Norwegian'],
            ['name' => 'Omen', 'iso2' => 'OM', 'iso3' => 'OMN', 'phone_code' => '968', 'nationality' => 'Omani'],
            ['name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'phone_code' => '92', 'nationality' => 'Pakistani'],
            ['name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'phone_code' => '680', 'nationality' => 'Palauan'],
            ['name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'phone_code' => '507', 'nationality' => 'Panamanian'],
            ['name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'phone_code' => '675', 'nationality' => 'Papua New Guinean, Papuan'],
            ['name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'phone_code' => '595', 'nationality' => 'Paraguayan'],
            ['name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'phone_code' => '51', 'nationality' => 'Peruvian'],
            ['name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'phone_code' => '63', 'nationality' => 'Philippine, Filipino'],
            ['name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'phone_code' => '48', 'nationality' => 'Polish'],
            ['name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'phone_code' => '351', 'nationality' => 'Portuguese'],
            ['name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'phone_code' => '974', 'nationality' => 'Qatari'],
            ['name' => 'Republic of Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'phone_code' => '373', 'nationality' => 'Moldovan'],
            ['name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'phone_code' => '40', 'nationality' => 'Romanian'],
            ['name' => 'Russian Federation', 'iso2' => 'RU', 'iso3' => 'RUS', 'phone_code' => '7', 'nationality' => 'Russian'],
            ['name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'phone_code' => '250', 'nationality' => 'Rwandan'],
            ['name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'phone_code' => '1', 'nationality' => 'Kittitian or Nevisian'],
            ['name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'phone_code' => '1', 'nationality' => 'Saint Lucian'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'phone_code' => '1', 'nationality' => 'Saint Vincentian, Vincentian'],
            ['name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'phone_code' => '685', 'nationality' => 'Samoan'],
            ['name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'phone_code' => '378', 'nationality' => 'Sammarinese'],
            ['name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'phone_code' => '239', 'nationality' => 'São Toméan'],
            ['name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'phone_code' => '966', 'nationality' => 'Saudi, Saudi Arabian'],
            ['name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'phone_code' => '221', 'nationality' => 'Senegalese'],
            ['name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'phone_code' => '381', 'nationality' => 'Serbian'],
            ['name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'phone_code' => '248', 'nationality' => 'Seychellois'],
            ['name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'phone_code' => '232', 'nationality' => 'Sierra Leonean'],
            ['name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'phone_code' => '65', 'nationality' => 'Singaporean'],
            ['name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'phone_code' => '421', 'nationality' => 'Slovak'],
            ['name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'phone_code' => '386', 'nationality' => 'Slovenian, Slovene'],
            ['name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'phone_code' => '677', 'nationality' => 'Solomon Island'],
            ['name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'phone_code' => '252', 'nationality' => 'Somali, Somalian'],
            ['name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'phone_code' => '27', 'nationality' => 'South African'],
            ['name' => 'South Sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'phone_code' => '211', 'nationality' => 'South Sudanese'],
            ['name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'phone_code' => '34', 'nationality' => 'Spanish'],
            ['name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'phone_code' => '94', 'nationality' => 'Sri Lankan'],
            ['name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'phone_code' => '249', 'nationality' => 'Sudanese'],
            ['name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'phone_code' => '597', 'nationality' => 'Surinamese'],
            ['name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'phone_code' => '46', 'nationality' => 'Swedish'],
            ['name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'phone_code' => '41', 'nationality' => 'Swiss'],
            ['name' => 'Syrian Arab Republic', 'iso2' => 'SY', 'iso3' => 'SYR', 'phone_code' => '963', 'nationality' => 'Syrian'],
            ['name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'phone_code' => '992', 'nationality' => 'Tajikistani'],
            ['name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'phone_code' => '255', 'nationality' => 'Tanzanian'],
            ['name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'phone_code' => '66', 'nationality' => 'Thai'],
            ['name' => 'Timor-Leste', 'iso2' => 'TL', 'iso3' => 'TLS', 'phone_code' => '670', 'nationality' => 'Timorese'],
            ['name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'phone_code' => '228', 'nationality' => 'Togolese'],
            ['name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'phone_code' => '676', 'nationality' => 'Tongan'],
            ['name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'phone_code' => '1', 'nationality' => 'Trinidadian or Tobagonian'],
            ['name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'phone_code' => '216', 'nationality' => 'Tunisian'],
            ['name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'phone_code' => '90', 'nationality' => 'Turkish'],
            ['name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'phone_code' => '993', 'nationality' => 'Turkmen'],
            ['name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'phone_code' => '688', 'nationality' => 'Tuvaluan'],
            ['name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'phone_code' => '256', 'nationality' => 'Ugandan'],
            ['name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'phone_code' => '380', 'nationality' => 'Ukrainian'],
            ['name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'phone_code' => '971', 'nationality' => 'Emirati, Emirian, Emiri'],
            ['name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'phone_code' => '44', 'nationality' => 'British, UK'],
            ['name' => 'United States', 'iso2' => 'US', 'iso3' => 'USA', 'phone_code' => '1', 'nationality' => 'American'],
            ['name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'phone_code' => '598', 'nationality' => 'Uruguayan'],
            ['name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'phone_code' => '998', 'nationality' => 'Uzbekistani, Uzbek'],
            ['name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'phone_code' => '678', 'nationality' => 'Ni-Vanuatu, Vanuatuan'],
            ['name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'phone_code' => '58', 'nationality' => 'Venezuelan'],
            ['name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'phone_code' => '84', 'nationality' => 'Vietnamese'],
            ['name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'phone_code' => '967', 'nationality' => 'Yemeni'],
            ['name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'phone_code' => '260', 'nationality' => 'Zambian'],
            ['name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'phone_code' => '263', 'nationality' => 'Zimbabwean'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
